### ISSUE TITLE
Opening the comfyui queue crashes the browser

### ISSUE THREAD

**Issue by bulldog68** [erosDiffusion/ComfyUI-enricos-nodes#66] opened 2024-09-23 14:55 UTC
hello, the node blocks the display of images in confortui see crashes the browser, tested with chrome and firefox. 
No Tasks Found
There are no tasks in the queue.
![Capture d’écran du 2024-09-23 16-38-18](https://github.com/user-attachments/assets/1b55d703-7770-491f-a8c6-7ba1ffe1e8e5)

**Comment by erosDiffusion** [comment] 2024-09-23 16:11
Hi the issue is there when opening the queue. Thanks for reporting.

As a temporary workaround, if you, can keep the queue/iage list closed to avoid the crash.

As I'm not getting any error / exceptions in the console it's quite hard to understand what's going on but I'm investigating.

**Comment by bulldog68** [comment] 2024-09-23 16:49
yes it is a solution, on the other hand a lot of node style
pythongosssss also blocks the browser when using compositor, it's a shame because this node is really handy.

**Comment by erosDiffusion** [comment] 2024-09-23 17:36
so, not entirely sure I can fix this.
it looks like the problem is in comfyui (or related to the node interaction with latest fromntend in comfy ui),
if you start with the legacy frontend there seems to be no issue:

https://github.com/comfyanonymous/ComfyUI#accessing-the-legacy-frontend
to start with legacy frontend use 
as commandline argument `--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest`


I will keep on investigating. at the root I think the problem lies with stopping the current flow with /interrupt api endpoing, some thread might be stuck but there is no error in the logs. also it might be due to some frontend stuff but again, not sure yet

**Comment by erosDiffusion** [comment] 2024-10-16 17:55
I'm still investigating what's causing the issue and it's cryptic.
for the time being I'm closing this.

if you don't want the issue just use the legacy toolbars until they are out of beta.

![image](https://github.com/user-attachments/assets/24a504da-ab35-4df7-baec-1f422f9c5733)

**Closed by erosDiffusion** 2024-10-16 17:55 UTC
Labels: bug
